# This code generates a dictionary with the query id as it's key and it's top 100 documents
# generated by lucene model, which uses standard analyzer, as it's corresponding value

import pickle
import os

# make the directory if it doesn't exist already
newpath = r'../../Encoded Data Structures (Phase 3)/'
if not os.path.exists(newpath):
    os.makedirs(newpath)

queryID_Top100Docs = {}                             # dictionary to store query id as key and it's corresponding
                                                    # top 100 documents as it's value

top_100_docs = []                                   # gets the top 100 documents

with open("../../../Phase 1/Task 3/Part A/Step 4/Lucene (Stopped)/Stopped_Lucene_Top100_Docs.txt", 'r', encoding='utf-8') as f:
   l = f.readlines()
l = [x.strip() for x in l]
top_100_docs.extend(l)

i = 1
c = 0
for doc in top_100_docs:
    if c < 100:
        if i not in queryID_Top100Docs:
            queryID_Top100Docs[i] = []
        queryID_Top100Docs[i].append(doc)
        c += 1
        continue
    i += 1
    queryID_Top100Docs[i] = []
    queryID_Top100Docs[i].append(doc)
    c = 1

# write the dictionary to a file, in encoded format using pickle library of python
output = open(newpath + 'Encoded-QueryID_Top100Docs_Stopped_Lucene.txt', 'wb')
pickle.dump(queryID_Top100Docs , output)
output.close()
